### ISSUE TITLE
序列化之后返回前端为什么只有 两个字段?

### ISSUE THREAD

**Issue by shyding** [Scalified/tree#11]
{
  "leaf": false,
  "root": true
}

**Comment by vbaidak** [comment]
Hi @shyding ! Thanks for using the Scalified Tree Library.

The TreeNode instance contains only service-based fields and methods. 
The TreeNode library contains a raw logic of building trees in java. It doesn't provide any compatible extensions for serialization / deserialization like Jackson, Gson etc.

If you want to see the data kept inside when you serialize the TreeNode, you should implement serializer logic yourself.
