### ISSUE TITLE
Deserialization with GSON

### ISSUE THREAD

**Issue by padaszewski** [Scalified/tree#14]
Hi there!
I've got a problem with deserialization of the tree structure using GSON. 
I'll do the following:
```java
Type type = new TypeToken<ArrayMultiTreeNode<Element>>(){}.getType();  
TreeNode<Element> tree = new Gson().fromJson(new FileReader(path), type);
System.out.println(tree.root());
```
it does the deserialization to the tree Object but when I try to call any method on it, like root or size, I got an Exception.

```
Exception in thread "main" java.lang.ClassCastException: class com.google.gson.internal.StringMap cannot be cast to class com.scalified.tree.TreeNode (com.google.gson.internal.StringMap and com.scalified.tree.TreeNode are in unnamed module of loader 'app')
	at com.scalified.tree.multinode.ArrayMultiTreeNode.traversePreOrder(ArrayMultiTreeNode.java:417)
	at com.scalified.tree.TreeNode.toString(TreeNode.java:775)
	at java.base/java.lang.String.valueOf(String.java:3352)
	at java.base/java.io.PrintStream.println(PrintStream.java:977)
	at TreeTest.main(TreeTest.java:37)
```

Besides, the JSON file which was generated from a tree with about 400 elements has 40k lines. These objects are quite large under the hood.
+ I tried also with Jackson but had same results

Is there any uniform possibility to proper serialize/deserialize the trees to/from JSON?

**Comment by vbaidak** [comment]
Hi, @padaszewski ! 
Thanks for using the **Scalified Tree Java Library**!

Unfortunately, the Library does not provide any serialization/deserialization mechanism *out-of-the-box* and is not intended to.

In order to make it work with the framework you choose (either `Gson` or `Jackson`), you need to do serialization / deserialization job manually on your side.
Here is a very rough example considering your case:
```java
String text = "{\"key1\": \"value1\", \"key2\": {\"key3\": \"value3\"}}";

JsonDeserializer<ArrayMultiTreeNode<String>> deserializer = new JsonDeserializer<ArrayMultiTreeNode<String>>() {
  @Override
  public ArrayMultiTreeNode<String> deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {
      JsonObject jsonObject = json.getAsJsonObject();
      ArrayMultiTreeNode<String> root = new ArrayMultiTreeNode<>("root");
      deserialize(jsonObject, root);
    return root;
  }

  private void deserialize(JsonObject jsonObject, ArrayMultiTreeNode<String> parent) {
    for (String key : jsonObject.keySet()) {
      ArrayMultiTreeNode<String> node = new ArrayMultiTreeNode<>(key);
      JsonElement element = jsonObject.get(key);
      if (element.isJsonObject()) {
        deserialize(element.getAsJsonObject(), node);
      } else {
        node.add(new ArrayMultiTreeNode<>(element.getAsString()));
      }
      parent.add(node);
    }
  }
};

Type type = new TypeToken<ArrayMultiTreeNode<String>>(){}.getType();
GsonBuilder builder = new GsonBuilder();
builder.registerTypeAdapter(type, deserializer);

Gson gson = builder.create();

System.out.println(gson.fromJson(text, type));
```

**Comment by padaszewski** [comment]
Thank's a lot for Your answer!
I build the serialization/deserialization but the problem was that the JSON file was too big for my purposes.
I enden up with an quite simple implementation of the generic tree that fits the usecase.
Anyway this was the best approach in java I found throughout the web for the n-ary tree, so thanks for that!
