### ISSUE TITLE
Building a tree, where the node.data values differ

### ISSUE THREAD

**Issue by glennDittmann** [Scalified/tree#16]
Hey @vbaidak  again, 

another thing I came across is, when I tried adding different (very similar) objects to the same tree.

So for my project I have some measuring objects, e.g. `TimeMeasure` and `DataMeasure`, which all inherit from the `MeasureDefinition` class. 
I would like to have a tree that consists of nodes with the data possibly taking any of these values.

Example:
```
DataMeasure data = new DataMeasure();
TimeMeasure time = new TimeMeasure();

MeasureDefinitionTreeNode<DataMeasure> n1 = new MeasureDefinitionTreeNode<>(data);
MeasureDefinitionTreeNode<TimeMeasure> n2 = new MeasureDefinitionTreeNode<>(time);

n1.add(n2);
```
(I have extended `MeasureDefinitionTreeNode` from `ArrayMultiTreeNode` , as suggested, but mainly to implement the equality check. So the rest is the same.)

However, as I see in [TreeNode.java](https://github.com/Scalified/tree/blob/master/tree/src/main/java/com/scalified/tree/TreeNode.java) (lines 90-98) all nodes in a tree must be of the same (non-) primitive type, correct?
```
/**
* Reference to the parent tree node. Is {@code null} if the current tree node is root
*/
protected TreeNode<T> parent;

/**
* Data store in the current tree node
*/
protected T data;  
```

Do you have any good idea on how to do this. Or do you think forking and beginning on the lowest level would be best?

Thanks again in advance for taking your time!

**Comment by vbaidak** [comment]
Hi @glennDittmann !

The `data` in a `tree` is of generic type `T`, meaning it can be any object type, thus non-primitive. The typing in the `tree` library is pretty much the same as the one implemented in the *Java Collections* framework - when you create a `List` or `Set` you specify a type and work with it. This, however, leads to a problem of [Covariance and Contravariance](https://dzone.com/articles/covariance-and-contravariance) in *Java*, which must be handled by the user.

In your example, everything will work fine unless you want to take your `data` object from either `n1` or `n2` - in this case, you'll get a `MeasureDefinition`, which is a supertype of both `DataMeasure` and `TimeMeasure`. If you need further to distinguish these types you can either check its instance (`instanceof`) or implement the necessary methods in the `MeasureDefinition` supertype and work with them.

**Comment by glennDittmann** [comment]
Hey @vbaidak,
thanks again for your answer!
Unfortunately it does not work. I get the error: 
`The method add(TreeNode<DataMeasure>) in the type MeasureDefinitionTreeNode<DataMeasure> is not applicable for the arguments (MeasureDefinitionTreeNode<TimeMeasure>)`

I believe that creating an object of the class `MeasureDefinitionTreeNode<MeasureDefinition>` injects the given type (here `DataMeasure`) into any appearance of `MeasureDefinition` in the extended class. (Where I basically swapped any `T` for the ground class `MeasureDefinition` in the methods i changed, i.e. `constructor` and `equals`.)
I will write a wrapper for my different MeasureDefinitions for now.

But am I overseeing any more easy solution?

**Comment by vbaidak** [comment]
Hi @glennDittmann ,

You can go with `MeasureDefinitionTreeNode` having the `MeasureDefinition` superclass type, e.g:
```java
class MeasureDefinitionTreeNode extends ArrayMultiTreeNode<MeasureDefinition> {

    public MeasureDefinitionTreeNode(MeasureDefinition data) {
        super(data);
    }

    public boolean equals(Object obj) {
        // ...
    }

}
```
Both `DataMeasure` and `TimeMeasure` must extend the `MeasureDefinition`. Then you'll be able to do this:
```java
DataMeasure data = new DataMeasure("dataMeasure");
TimeMeasure time = new TimeMeasure(System.currentTimeMillis());

MeasureDefinitionTreeNode n1 = new MeasureDefinitionTreeNode(data);
MeasureDefinitionTreeNode n2 = new MeasureDefinitionTreeNode(time);
n1.add(n2);
```

However, you won't be able to do this:
```java
TimeMeasure n2Time = n2.data() // compilation error (MeasureDefinition expected)
```

Hope this helps

**Comment by glennDittmann** [comment]
Hey @vbaidak,
thanks a lot for your help ! I really appreciate you taking your time to help me.
This way it worked!
So the crucial step was omitting the generic type in the new class definition. I don't totally understand, why this makes the difference in the call of `add()` or in general what differences in the class this implies in general.

Just for being complete, here's what I did:

```java
class MeasureDefinitionTreeNode<MeasureDefinition> extends ArrayMultiTreeNode<MeasureDefinition> {

    public MeasureDefinitionTreeNode(MeasureDefinition data) {
        super(data);
    }

    public boolean equals(Object obj) {
        // ...
    }

}
```
Maybe you can shed some light on this subtle difference?

Anyways, thanks again for your help!

**Comment by vbaidak** [comment]
NP, @glennDittmann 

In Java, when you declare a class with diamonds `<>`, it means you declare it to be generic. So, in your case `MeasureDefinitionTreeNode<MeasureDefinition>` is the same as `MeasureDefinitionTreeNode<T>` or any other placeholder (by convention can be `<T>`, `<K>` etc.). In such a case, you need to specify the type explicitly during instantiation of this `tree` object:

```java
MeasureDefinitionTreeNode<DataMeasure> n1 = new MeasureDefinitionTreeNode<>(data);
```
And, of course, this forces you to use only the `DataMeasure` type.

For your case, you do not need to mark your `MeasureDefinitionTreeNode` class as generic, since you specify the type on an `ArrayMultiTreeNode<MeasureDefinition>` class.

**Comment by glennDittmann** [comment]
Ahhh, yes. Now everything is clear. I was still assuming my `<MeasureDefinition>` was of type `MeasureDefinition`, whereas it was a generic placeholder the whole time and I should have written `<T>` instead. 😄 

Thanks for clarifying!
