### ISSUE TITLE
Such a great library - Is this not maintained anymore ? 

### ISSUE THREAD

**Issue by 0xvoila** [Scalified/tree#18]
Hi, 

It is really great library having almost all the features needed with respect to trees. I saw last release has happened in 2015, is it not maintained any more ?

**Comment by vbaidak** [comment]
Hi!

Thank you for such a positive evaluation of our work!
Unfortunately, new releases are not planned.

However, we are still supporting this library and will help in case of any issues

**Comment by 0xvoila** [comment]
Hi @vbaidak : Thank you for the response. 

@vbaidak : I have a requirement where I want to construct the K ary tree from its `preorder` traversal. Is there any way I can do that using the library. 

**More Context** 

I am using this library to create the `Merkle trees` and transfer them among machines for data replication.  Now when `machine A` sends its Merkle tree to `machine B` , it sends its `preoder traversal` like `["hash1", "hash2", "hash3", "hash4", "hash5"]`.
 
On `machine B` I need to create the `Merkle` from its `preorder traversal` so that I can compare it with `merkle` of its own ( i..e `Machine B` 

So I was thinking if this library supports this use case i.e. creating the tree from its `preorder` traversal.
