### ISSUE TITLE
Tree Representation

### ISSUE THREAD

**Issue by amitjoy** [Scalified/tree#4]
I am wondering if there is any way to print the tree structure in console.

**Comment by ji-zhou** [comment]
@amitjoy There is a toString() in TreeNode, you can have a try.
see:https://github.com/Scalified/tree/blob/6ba25dc59b6ea3be97c43a9a0de99fc95c410606/tree/src/main/java/com/scalified/tree/TreeNode.java#L753

**Comment by amitjoy** [comment]
Thanks @ji-zhou for the quick response
