### ISSUE TITLE
how to build this library into android studio?

### ISSUE THREAD

**Issue by Cendra123** [Scalified/tree#9]

**Comment by vbaidak** [comment]
Hi @Cendra123,

In order to use the **Tree Library** in your project, you need to add it via Gradle dependency as follows:
```groovy
dependencies {
	compile 'com.scalified:tree:0.2.5'
}
```

> If this still doesn't answer your question, please describe in more detail what you are trying to achieve and what issues you are facing with.

**Comment by Cendra123** [comment]
thankyou @vbaidak
